APP_NAME = "GlobalCon Calculator"

WEIGHTS = {
    "Completed": 50,
    "Core cards": 1,
    "Original art": 100,
    "Make ready": 15,
    "Testprints": 13,
    "Playtests": 13,
    "Original artist alters": 15,
    "Artist Proofs": 8,
    "Summer": 10,
    "Revised alpha-cut": 5,
    "Fourth alpha-cut": 5,
    "Square corners": 5,
    "Miscut": 9,
    "Miscut NFC": 4,
    "Offcenters": 3,
    "Crimps": 8,
    "Ink problems": 8,
    "Garfield signed": 10,
    "Signed": 2,
    "Graded BGS 8.5": 4,
    "Graded BGS 9": 7,
    "Graded BGS 9.5": 12,
    "Graded BGS 10": 20,
    "Graded PSA 9": 7,
    "Graded PSA 10": 12,
    "Other rarities": 3,
}

LOGO_FILE = "documentation/GlobalCon_logo.png"

FONT = "Helvetica 14 bold"

RESULTS_FOLDER = "DATA/RESULTS"

RESULTS_NOCOMPETE_FOLDER = "DATA/RESULTS_NOCOMPETE"

DEFAULT_MESSAGES = {
    "Completed": "1 if completed, 0 otherwise",
    "Core cards": "Amount of distinct core cards owned (max 500)",
    "Original art": "Amount of original arts owned (max 10)",
    "Make ready": "Owned make ready's (max 2)",
    "Testprints": "Owned testprints (max 5)",
    "Playtests": "Amount of distinct playtests owned (max 10)",
    "Original artist alters": "Amount of original artist alters owned (max 10)",
    "Artist Proofs": "Amount of distinct artist proofs owned (max 30)",
    "Summer": "Owned summer cards, 0 if not owned & doesn't exist, -1 if not owned & exists (max 4)",
    "Revised alpha-cut": "1 if owned, 0 if not owned",
    "Fourth alpha-cut": "1 if owned, 0 if not owned",
    "Square corners": "1 if owned, 0 if not owned",
    "Miscut": "Amount of miscuts owned (max 4)",
    "Miscut NFC": "Amount of NFC miscuts owned (max 4)",
    "Offcenters": "Amount of offcenters owned (max 4)",
    "Crimps": "Amount of crimps owned (max 4)",
    "Ink problems": "Amount of cards with any ink problems owned (max 4)",
    "Garfield signed": "1 if owned, 0 if not owned",
    "Signed": "Amount of distinct signed cards owned (max 10)",
    "Graded BGS 8.5": "Amount of BGS8.5's owned (max 4)",
    "Graded BGS 9": "Amount of BGS9's owned (max 4)",
    "Graded BGS 9.5": "Amount of BGS9.5's owned (max 4)",
    "Graded BGS 10": "Amount of BGS10's owned (max 4)",
    "Graded PSA 9": "Amount of PSA9's owned (max 4)",
    "Graded PSA 10": "Amount of PSA10's owned (max 4)",
    "Other rarities": "Amount of other distinct rarities owned (max 50)",
}

RANGES = {
    "Completed": [0, 1],
    "Core cards": [0, 500],
    "Original art": [0, 10],
    "Make ready": [0, 2],
    "Testprints": [0, 5],
    "Playtests": [0, 10],
    "Original artist alters": [0, 10],
    "Artist Proofs": [0, 30],
    "Summer": [-1, 4],
    "Revised alpha-cut": [0, 1],
    "Fourth alpha-cut": [0, 1],
    "Square corners": [0, 1],
    "Miscut": [0, 4],
    "Miscut NFC": [0, 4],
    "Offcenters": [0, 4],
    "Crimps": [0, 4],
    "Ink problems": [0, 4],
    "Garfield signed": [0, 1],
    "Signed": [0, 10],
    "Graded BGS 8.5": [0, 4],
    "Graded BGS 9": [0, 4],
    "Graded BGS 9.5": [0, 4],
    "Graded BGS 10": [0, 4],
    "Graded PSA 9": [0, 4],
    "Graded PSA 10": [0, 4],
    "Other rarities": [0, 50],
}
