LANGUAGE_IDS = {
    1: "English",
    2: "Italian",
    3: "German",
    4: "French",
    5: "Spanish",
    6: "Portuguese",
    7: "Japanese",
    8: "Korean",
    9: "S-Chinese",
    10: "T-Chinese",
    11: "Russian",
}

LANGUAGES = {
    "Limited Edition Alpha": [1],
    "Limited Edition Beta": [1],
    "Unlimited Edition": [1],
    "Revised Edition": [1, 2, 3, 4],
    "Foreign Black Border": [2, 3, 4],
    "Summer Magic / Edgar": [],
    "Fourth Edition": [1, 2, 3, 4, 5, 6, 7],
    "Fourth Edition Foreign Black Border": [5, 6, 7, 8, 9],
    "Fifth Edition": [1, 2, 3, 4, 5, 6, 7, 8, 10],
    "Classic Sixth Edition": [1, 2, 3, 4, 5, 6, 7, 9, 10],
    "Seventh Edition": [1, 2, 3, 4, 5, 6, 7, 9, 10],
    "Eighth Edition": [1, 2, 3, 4, 5, 6, 7, 9, 10],
    "Ninth Edition": [1, 2, 3, 4, 5, 6, 7, 9, 11],
    "Tenth Edition": [1, 2, 3, 4, 5, 6, 7, 9, 11],
    "Magic 2010": [1, 2, 3, 4, 5, 6, 7, 9, 11],
    "Magic 2011": [1, 2, 3, 4, 5, 6, 7, 9, 11],
    "Magic 2012": [1, 2, 3, 4, 5, 6, 7, 9, 11],
    "Magic 2013": [1, 2, 3, 4, 5, 6, 7, 8, 9, 11],
    "Arabian Nights": [1],
    "Antiquities": [1],
    "Legends": [1],
    "The Dark": [1, 2],
    "Collectors’ Edition": [1],
    "Intl. Collectors’ Edition": [1],
    "Salvat 2011": [5],
    "Battle Royale Box Set": [1],
    "Introductory Two-Player Set": [1, 2, 3, 4, 5, 7],
    "Rivals Quick Start Set": [],
    "Anthologies": [1],
    "Secret Lair Drop": [1],
    "Rinascimento": [2],
    "Renaissance": [3, 4],
    "World Championship Decks 1997": [1],
    "World Championship Decks 1998": [1],
    "World Championship Decks 1999": [1],
    "World Championship Decks 2000": [1],
    "World Championship Decks 2004": [1],
    "Eternal Masters": [1, 7, 9],
    "Masters 25": [1, 7, 9],
    "Mystery Booster": [1],
    "Beatdown Box Set": [1],
    "Mirrodin": [1, 2, 3, 4, 5, 6, 7, 9, 10],
    "Magic Player Rewards 2005": [1],
    "Fallen Empires": [1],
    "Pro Tour Collector Set": [1],
    "From the Vault: Twenty": [1],
    "Tempest": [1, 2, 3, 4, 5, 6, 7, 8, 10],
    "Friday Night Magic 2000": [1],
    "Friday Night Magic 2003": [1],
    "Friday Night Magic 2004": [1],
    "Archenemy": [1],
    "Premium Deck Series: Graveborn": [1],
    "Premium Deck Series: Fire and Lightning": [1],
    "Ultimate Box Topper": [1],
    "Ultimate Masters": [1, 7],
    "Jumpstart": [1],
    "Commander Collection: Black": [],
    "Media Inserts": [],
    "Vintage Championship": [],
    "Arena League 1996": [1],
    "Darksteel": [1, 2, 3, 4, 5, 6, 7, 9],
    "Commander 2013": [1, 2, 3, 4, 5, 7],
    "Iconic Masters": [1, 7, 9],
    "The List": [1],
    "Judge Gift Cards 2008": [1],
    "Judge Gift Cards 2020": [1],
    "Strixhaven Mystical Archive": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    "Ice Age": [1, 2, 3, 4, 5, 6],
    "Mercadian Masques": [1, 2, 3, 4, 5, 6, 7, 10],
    "Coldsnap Theme Decks": [1, 2, 3, 4, 5, 6, 7, 9],
    "Commander 2011": [1, 2, 3, 4, 5, 7],
    "Legacy Championship": [],
    "Conspiracy": [1, 7, 9],
    "Commander 2015": [1, 2, 3, 4, 5, 7, 9],
    "Signature Spellbook: Jace": [1],
    "Commander 2018": [1, 2, 3, 4, 5, 6, 7],
    "Double Masters": [1, 3, 4, 7, 9],
    "Commander 2021": [1, 2, 3, 4, 5, 6, 7, 9, 10, 11],
    "Forgotten Realms Commander": [1, 2, 3, 4, 5, 6, 7, 9, 10, 11],
    "Mirage": [1, 2, 3, 4, 5, 6, 7, 10],
    "Portal": [1, 3, 4, 5, 7, 9, 10],
    "Portal Second Age": [1, 2, 3, 4, 5, 6, 7],
    "Starter 1999": [1],
    "Portal Three Kingdoms": [1, 7, 9, 10],
    "Champions of Kamigawa": [1, 2, 3, 4, 5, 6, 7, 9],
    "Urza's Saga": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Time Spiral Timeshifted": [1, 2, 3, 4, 5, 6, 7, 9, 10, 11],
    "Magic Player Rewards 2007": [1],
    "Conspiracy: Take the Crown": [1, 7, 9],
    "Core Set 2020": [1, 2, 3, 4, 5, 6, 7, 8, 9, 11],
    "Judge Gift Cards 1998": [1],
    "Magic Player Rewards 2010": [1],
    "Modern Masters 2015": [1, 7, 9],
    "Archenemy: Nicol Bolas": [1],
    "MagicFest 2019": [1],
    "Jumpstart: Historic Horizons": [1],
    "Judge Gift Cards 2013": [1],
    "Homelands": [1],
    "Commander Legends: Battle for Baldur's Gate": [1, 2, 3, 4, 5, 6, 7, 9],
    "Rise of the Eldrazi": [1, 2, 3, 4, 5, 6, 7, 9, 11],
    "Rise of the Eldrazi Promos": [1, 2, 3, 4, 5, 7],
    "Pro Tour Promos": [1],
    "Friday Night Magic 2005": [1],
    "From the Vault: Exiled": [1],
    "Duel Decks: Jace vs. Chandra": [1, 7],
    "Duel Decks: Divine vs. Demonic": [1],
    "Duel Decks Anthology: Jace vs. Chandra": [1],
    "Duel Decks Anthology: Divine vs. Demonic": [1],
    "Duel Decks: Garruk vs. Liliana": [1],
    "Duel Decks: Ajani vs. Nicol Bolas": [1],
    "Duel Decks Anthology: Garruk vs. Liliana": [1],
    "Duels of the Planeswalkers": [1],
    "Duel Decks: Izzet vs. Golgari": [1, 7],
    "Duel Decks: Jace vs. Vraska": [1, 7],
    "Visions": [1, 2, 3, 4, 5, 6, 7, 8, 10],
    "Zendikar": [1, 2, 3, 4, 5, 6, 7, 8, 9, 11],
}

ARTIST_PROOFS = {
    "Limited Edition Beta": ["English"],
    "Revised Edition": ["English", "Italian"],
    "Fourth Edition": ["English", "Italian", "Japanese", "T-Chinese"],
    "Fifth Edition": ["English"],
    "Classic Sixth Edition": ["English"],
    "Seventh Edition": ["English"],
    "Eighth Edition": ["English"],
    "Ninth Edition": ["English"],
    "Tenth Edition": ["English"],
    "Magic 2010": ["English"],
    "Antiquities": ["English"],
    "Legends": ["English"],
    "The Dark": ["English"],
    "Fallen Empires": ["English"],
    "Chronicles": ["English"],
    "Ice Age": ["English", "Italian", "French", "Spanish", "Portuguese"],
    "Homelands": ["English"],
    "Alliances": ["English"],
    "Mirage": ["English"],
    "Eternal Masters": ["English", "English (FOIL)", "Japanese", "Japanese (FOIL)",
                        "S-Chinese", "S-Chinese (FOIL)"]
}

SPECIFIC_RARITIES = {
    "Revised Edition": [
        "Summer Magic [English]",
        "Revised Miscut NFC [English]",
    ],
    "Fourth Edition": [
        "Fourth Edition Alternate [English]",
    ],
}

GENERIC_RARITIES = [
    "Miscut",
    "Crimp",
    "Signed",
    "Sunbleached",
    "Albino",
    "Square corners",
]

PLAYTESTS_SETS = {
    "Limited Edition Alpha": ["Gamma", "Delta", "Epsilon"],
    "Ice Age": ["Ice Age Grey", "Ice Age Pink"],
    "The Dark": ["The Dark"],
}

NON_EXISTING_PLAYTESTS = {
    "Limited Edition Alpha": [
        "Holy Armor",
        "Island Sanctuary",
        "Lance",
        "Personal Incarnation",
        "Samite Healer",
        "Veteran Bodyguard",
        "Creature Bond",
        "Drain Power",
        "Invisibility",
        "Pirate Ship",
        "Power Leak",
        "Psychic Venom",
        "Spell Blast",
        "Stasis",
        "Nettling Imp",
        "Paralyze",
        "Plague Rats",
        "Royal Assassin",
        "Will-O'-The-Wisp",
        "Word of Command",
        "Dragon Whelp",
        "Dwarven Demolition Team",
        "Dwarven Warriors",
        "Goblin Balloon Brigade",
        "Keldon Warlord",
        "Orcish Artillery",
        "Orcish Oriflamme",
        "Raging River",
        "Sedge Troll",
        "Stone Giant",
        "Birds of Paradise",
        "Elvish Archers",
        "Gaea's Liege",
        "Ley Druid",
        "Verduran Enchantress",
        "Wall of Ice",
        "Web",
        "Clockwork Beast",
        "Conservator",
        "Illusionary Mask",
        "Badlands",
        "Bayou",
        "Plateau",
        "Savannah",
        "Scrubland",
        "Taiga",
        "Tropical Island",
        "Tundra",
        "Underground Sea",
    ]
}

NON_EXISTING_CARDS = {
    "Fifth Edition": {
        "T-Chinese": {
            "non-foil": [
                "Æther Storm",
                "Amulet of Kroog",
                "Angry Mob",
                "Animate Dead",
                "Animate Wall",
                "Anti - Magic Aura",
                "Arenson's Aura",
                "Armor of Faith",
                "Ashnod's Transmogrant",
                "Aspect of Wolf",
                "Aurochs",
                "Ball Lightning",
                "Barbed Sextant",
                "Battering Ram",
                "Benalish Hero",
                "Blessed Wine",
                "Blood Lust",
                "Brainwash",
                "Breeding Pit",
                "Carapace",
                "Clay Statue",
                "Cloak of Confusion",
                "Colossus of Sardia",
                "Craw Giant",
                "D'Avenant Archer",
                "Derelor",
                "Disintegrate",
                "Drudge Skeletons",
                "Dwarven Soldier",
                "Enervate",
                "Eternal Warrior",
                "Eye for an Eye",
                "Fallen Angel",
                "Flame Spirit",
                "Flare",
                "Force of Nature",
                "Force Spike",
                "Foxfire",
                "Game of Chaos",
                "Grapeshot Catapult",
                "Heal",
                "Hecatomb",
                "Helm of Chatzuk",
                "Homarid Warrior",
                "Hungry Mist",
                "Hurkyl's Recall",
                "Icatian Phalanx",
                "Imposing Visage",
                "Ironclaw Curse",
                "Ironclaw Orcs",
                "Kjeldoran Dead",
                "Kjeldoran Royal Guard",
                "Kjeldoran Skycaptain",
                "Krovikan Fetish",
                "Leviathan",
                "Lord of the Pit",
                "Lost Soul",
                "Mana Clash",
                "Marsh Viper",
                "Mesa Pegasus",
                "Mind Ravel",
                "Mind Warp",
                "Necropotence",
                "Orcish Captain",
                "Orcish Oriflamme",
                "Orgg",
                "Panic",
                "Phantasmal Forces",
                "Phantasmal Terrain",
                "Pikemen",
                "Pit Scorpion",
                "Portent",
                "Prismatic Ward",
                "Regeneration",
                "Scathe Zombies",
                "ScrybSprites",
                "Sea Sprite",
                "Serpent Generator",
                "Shield Bearer",
                "Skull Catapult",
                "Soul Barrier",
                "Stampede",
                "Tarpan",
                "The Brute",
                "The Wretched",
                "Time Bomb",
                "Torture",
                "Touch of Death",
                "Twiddle",
                "Unholy Strength",
                "Unstable Mutation",
                "Updraft",
                "Urza's Avenger",
                "Urza's Bauble",
                "Venom",
                "Wall of Bone",
                "War Mammoth",
                "Wolverine Pack",
                "Zombie Master"
            ]
        }
    },
    "Urza's Legacy": {
        "T-Chinese": {
            "foil": []
        }
    },
    "Urza's Destiny": {
        "T-Chinese": {
            "foil": []
        }
    },
    "Mercadian Masques": {
        "T-Chinese": {
            "foil": []
        }
    },
    "Invasion": {
        "S-Chinese": {
            "foil": []
        }
    },
    "Jumpstart: Historic Horizons": {
        "English": {
            "foil": []
        }
    }
}
